=== go4st/FOR-IDENT/filehandler/src/main/resources/config/dtd/readerConfig.dtd
<!ELEMENT file (sheets)>
<!ATTLIST file format (97|2007|97-2007) #IMPLIED
			   quoteChar CDATA #IMPLIED
			   delimiterChar CDATA #IMPLIED
			   endOfLineSymbol CDATA #IMPLIED
>
<!ELEMENT sheets (sheet+)>
<!ELEMENT sheet (groups)>
<!ATTLIST sheet id ID #REQUIRED
				name CDATA #IMPLIED
				identifierRow CDATA #REQUIRED
				contentRow CDATA #REQUIRED
>
<!ELEMENT groups (group+)>
<!ELEMENT group (columns)>
<!ATTLIST group id ID #REQUIRED
				requiredColumns CDATA #REQUIRED
>
<!ELEMENT columns (column+)>
<!ELEMENT column EMPTY>
<!ATTLIST column id ID #REQUIRED
				 name CDATA #REQUIRED 
		 		 multiple (true|false) #REQUIRED
>

=== go4st/FOR-IDENT/filehandler/src/main/resources/config/silistsinglesourceconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE file SYSTEM "dtd/readerConfig.dtd">
<file format="2007">
    <sheets>
        <sheet id="substances" name="Substances" identifierRow="0" contentRow="1" >
        	<groups>
        		<group id = "G1" requiredColumns = "all">
		            <columns>
		                <column id ="name" name="Name" multiple="false" />
		                <column id ="cas" name="CAS" multiple="false" />
		                <column id ="ec" name="EC number" multiple="false" />
		                <column id ="smiles" name="SMILES" multiple="false" />
		                <column id ="iupac" name="IUPAC" multiple="false" />
		                <column id ="formula" name="Formula" multiple="false" />
		                <column id ="mass" name="Mass" multiple="false" />
		                <column id ="pka" name="PKa" multiple="false" />
		                <column id ="tonnage" name="Tonnage" multiple="false" />
		                <column id ="boilingPoint" name="Boiling point" multiple="false" />
		                <column id ="logp" name="logP" multiple="true" />
		                <column id ="logd" name="logD" multiple="true" />
		                <column id ="waterSolubility" name="Water solubility" multiple="true" />
		                <column id ="additionalNames" name="Additional names" multiple="true" />
		            </columns>
            	</group>
            </groups>
        </sheet>
    </sheets>
</file>

=== go4st/FOR-IDENT/filehandler/src/main/resources/config/silistmultisourceconfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE file SYSTEM "dtd/readerConfig.dtd">
<file format="2007">
    <sheets>
        <sheet id="substances" name="Substances" identifierRow="0" contentRow="1" >
        	<groups>
        		<group id = "G1" requiredColumns = "all">
		            <columns>
		                <column id ="name" name="Name" multiple="false" />
		                <column id ="nameSource" name="Name source" multiple="false" />
		                <column id ="cas" name="CAS" multiple="false" />
		                <column id ="casSource" name="CAS source" multiple="false" />
		                <column id ="ec" name="EC number" multiple="false" />
		                <column id ="ecSource" name="EC number source" multiple="false" />
		                <column id ="smiles" name="SMILES" multiple="false" />
		                <column id ="smilesSource" name="SMILES source" multiple="false" />
		                <column id ="iupac" name="IUPAC" multiple="false" />
		                <column id ="iupacSource" name="IUPAC source" multiple="false" />
		                <column id ="formula" name="Formula" multiple="false" />
		                <column id ="formulaSource" name="Formula source" multiple="false" />
		                <column id ="mass" name="Mass" multiple="false" />
		                <column id ="massSource" name="Mass source" multiple="false" />
		                <column id ="pka" name="PKa" multiple="false" />
		                <column id ="pkaSource" name="PKa source" multiple="false" />
		                <column id ="tonnage" name="Tonnage" multiple="false" />
		                <column id ="tonnageSource" name="Tonnage source" multiple="false" />
		                <column id ="boilingPoint" name="Boiling point" multiple="false" />
		                <column id ="boilingPointSource" name="Boiling point source" multiple="false" />
		                <column id ="logp" name="logP" multiple="true" />
		                <column id ="logpSource" name="logP source" multiple="true" />
		                <column id ="logd" name="logD" multiple="true" />
		                <column id ="logdSource" name="logD source" multiple="true" />
		                <column id ="waterSolubility" name="Water solubility" multiple="true" />
		                <column id ="waterSolubilitySource" name="Water solubility source" multiple="true" />
		                <column id ="additionalNames" name="Additional names" multiple="true" />
		                <column id ="additionalNamesSource" name="Additional names source" multiple="true" />
		            </columns>
            	</group>
            </groups>
        </sheet>
    </sheets>
</file>

=== go4st/FOR-IDENT/filehandler/src/main/resources/config/reader1Config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE file SYSTEM "dtd/readerConfig.dtd">
<file format="97">
    <sheets>
        <sheet id = "S0" name="calibration" identifierRow="0" contentRow="3" >
        	<groups>
        		<group id = "G1" requiredColumns = "all">
		            <columns>
		                <column id = "C0" name="substance name" multiple="false" />
		                <column id = "C1" name="logp" multiple="false" />
		                <column id = "C2" name="rt" multiple="true" />
		            </columns>
	            </group>
            </groups>
        </sheet>
        <sheet id = "S1" identifierRow="0" contentRow="3" >
       		<groups>
        		<group id = "G2" requiredColumns = "all">
		            <columns>
		                <column id = "C3" name="substance name" multiple="false" />
		                <column id = "C4" name="logp" multiple="false" />
		                <column id = "C5" name="rt" multiple="true" />
		            </columns>
            	</group>
            	<group id = "G3" requiredColumns = "1">
            		<columns>
            			<column id = "C6" name="bla" multiple="false" />
            		</columns>
            	</group>
        	</groups>
        </sheet>
    </sheets>
</file>

=== go4st/FOR-IDENT/filehandler/src/main/resources/config/reader3Config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE file SYSTEM "dtd/readerConfig.dtd">
<file quoteChar="&quot;" delimiterChar="," endOfLineSymbol="\n">
    <sheets>
        <sheet id = "S0" identifierRow="0" contentRow="1" >
        	<groups>
        		<group id = "G1" requiredColumns = "all">
		            <columns>
		                <column id = "C0" name="#" multiple="false" />
		                <column id = "C1" name="Name" multiple="false" />
		                <column id = "C2" name="Formula" multiple="false" />
		                <column id = "C3" name="Include" multiple="false" />
		                <column id = "C4" name="Mass (Da)" multiple="false" />
		                <column id = "C5" name="Found At Mass (Da)" multiple="false" />
		                <column id = "C6" name="Control Found At Mass (Da)" multiple="false" />
		                <column id = "C7" name="Width (Da)" multiple="false" />
		                <column id = "C8" name="Adduct" multiple="false" />
		                <column id = "C9" name="Expected RT (min)" multiple="false" />
		                <column id = "C10" name="RT Width (min)" multiple="false" />
		                <column id = "C11" name="Found At RT (min)" multiple="false" />
		                <column id = "C12" name="Control Found At RT (min)" multiple="false" />
		                <column id = "C13" name="Library Score" multiple="false" />
		                <column id = "C14" name="Library Hit" multiple="false" />
		                <column id = "C15" name="Formula Finder Result" multiple="false" />
		                <column id = "C16" name="Intensity" multiple="false" />
		                <column id = "C17" name="Control Intensity" multiple="false" />
		                <column id = "C18" name="Known Concentration" multiple="false" />
		                <column id = "C19" name="Calculated Concentration" multiple="false" />
		                <column id = "C20" name="Area" multiple="false" />
		                <column id = "C21" name="Control Area" multiple="false" />
		                <column id = "C22" name="Isotope" multiple="false" />
		                <column id = "C23" name="Threshold (cps)" multiple="false" />
		                <column id = "C24" name="Threshold (ratio of control)" multiple="false" />
		                <column id = "C25" name="Formula Finder Score" multiple="false" />
		                <column id = "C26" name="Int Std" multiple="false" />
		                <column id = "C27" name="Combined Score" multiple="false" />
		                <column id = "C28" name="Mass Error Score" multiple="false" />
		                <column id = "C29" name="RT Score" multiple="false" />
		                <column id = "C30" name="Isotope Score" multiple="false" />
		                <column id = "C31" name="Non-Targeted Peak" multiple="false" />
		                <column id = "C32" name="S:N" multiple="false" />
		                <column id = "C33" name="Fragment Mass (Da)" multiple="false" />
		                <column id = "C34" name="Comments" multiple="false" />
		                <column id = "C35" name="Extraction Mass (Da)" multiple="false" />
		                <column id = "C36" name="Error (ppm)" multiple="false" />
		                <column id = "C37" name="Control Error (ppm)" multiple="false" />
		                <column id = "C38" name="Error (mDa)" multiple="false" />
		                <column id = "C39" name="Control Error (mDa)" multiple="false" />
		                <column id = "C40" name="RT Delta (min)" multiple="false" />
		                <column id = "C41" name="Control RT Delta (min)" multiple="false" />
		                <column id = "C42" name="RT % Error" multiple="false" />
		                <column id = "C43" name="Control RT % Error" multiple="false" /> 
		            </columns>
	            </group>
            </groups>
        </sheet>
    </sheets>
</file>
